language: cpp
script:
- cmake -H. -B_builds -DBUILD_TESTS=ON
- cmake --build _builds
- cmake --build _builds --target test -- ARGS=--verbose
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
